name: CI

on:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    name: Test and build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 12.x
      - uses: bahmutov/npm-install@v1
      - name: Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn coverage

      - uses: codecov/codecov-action@v1

  push-docker-image:
    needs: [lint-and-test]
    name: Push Docker Image To Repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: docker build -t nazmialtun/mockizen:${{ github.run_number }} -t nazmialtun/mockizen:latest .
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push Docker Images to Registry
        run: |
          docker push nazmialtun/mockizen:latest
          docker push nazmialtun/mockizen:${{ github.run_number }}
